### PR TITLE
Add CORS headers

### PR DESCRIPTION
**Pull request by crobby**
Adding rs/cors middleware to handle adding our CORS
headers which will allow oshinko-rest to be called from places
other than the same pod (ajax calls in browsers).

### CODE REVIEW

**Comment by elmiko** [comment]
this looks good on cursory examination, i'll give it a local test

**Comment by sub-mod** [comment]
LGTM
Tested this locally with webui @ https://192.168.0.100:9000 and rest @ http://127.0.0.1:42000
UI was able to make calls to http, should work with https Route too.

**Comment by crobby** [comment]
All my testing was done with the https route in openshift, so I think we have it covered.

**Comment by elmiko** [comment]
lgtm, thanks Chad!

**Pull request merged**
