### PR TITLE
Reference configmaps directly for cluster configs

### PR DESCRIPTION
**Pull request by tmckayus**
Instead of reading named cluster configs from a volumne mounted
on the oshinko pod, just reference the config maps directly using
the kube client.

### CODE REVIEW

**Comment by tmckayus** [comment]
This is an impl for https://github.com/radanalyticsio/oshinko-specs/pull/8

**Comment by tmckayus** [comment]
Do not merge quite yet. 

Note, needs some description text changes in associated s2i templates.
Also seems to be a bug when reading a configmap created from a directory with --from-file. Handling of integers is off in that case ...

**Comment by tmckayus** [comment]
Okay, this should be good now.

**Comment by tmckayus** [comment]
but of course I forgot to update the readme ....

**Comment by elmiko** [comment]
i'm still good with this, are you going to update the readme or shall we merge?

**Comment by tmckayus** [comment]
going to update the readme ... then I'll merge

**Pull request merged**
